---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guided-postgres-secret
  namespace: guided
spec:
  encryptedData:
    GUIDED_APP_PASSWORD: Ag==
    GUIDED_APP_USER: Ag==
    POSTGRES_DB: Ag==
    POSTGRES_PASSWORD: Ag==
    POSTGRES_USER: Ag==
    password: Ag==
    username: Ag==
  template:
    metadata:
      name: guided-postgres-secret
      namespace: guided
