apiVersion: v1
kind: Service
metadata:
  name: guided-postgres
  namespace: guided
spec:
  selector:
    cnpg.io/cluster: guided-db
    role: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
